In [1]:
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd
import numpy as np

In [2]:
iris = load_iris()

In [3]:
X = pd.DataFrame(data = iris.data[:112:], columns = iris.feature_names)
X.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
y = pd.DataFrame(data=iris.target[:112], columns = ['irisType'])
y = y.to_numpy()
y = y.reshape(-1, 1)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
mdlPercept = Perceptron()

In [6]:
mdlPercept.fit(X_train, y_train)

In [8]:
y_pred = mdlPercept.predict(X_test)

In [9]:
accuracy = accuracy_score(y_test, y_pred)

In [10]:
print("Accuracy:", accuracy)

Accuracy: 1.0


In [11]:
print("Perceptron Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

Perceptron Confusion Matrix:
 [[13  0  0]
 [ 0  9  0]
 [ 0  0  1]]
